gui:
  wrapMainPanel: true
  sidePanelWidth: 0.333
  expandFocusedSidePanel: true # set to true for auto-expand focused panel
  containerStatusHealthStyle: "short" # 'long' | 'short' | 'icon'

stats:
  graphs:
    - caption: CPU (%)
      statPath: DerivedStats.CPUPercentage
      color: cyan
    - caption: Memory (%)
      statPath: DerivedStats.MemoryPercentage
      color: green

customCommands:
  containers:
    - name: bash
      attach: true
      command: "docker exec -it {{ .Container.ID }} bash"
    - name: dive
      attach: true
      command: "dive {{ .Container.Image.Name }}"
    - name: sh
      attach: true
      command: "docker exec -it {{ .Container.ID }} sh"
  images:
    - name: dive
      attach: true
      command: "dive {{ .Image.Name }}"
