[".oh-my-zsh/custom/plugins/auto-notify"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/MichaelAquilina/zsh-auto-notify/archive/master.tar.gz"

[".oh-my-zsh/custom/plugins/git-extra-commands"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/unixorn/git-extra-commands/archive/main.tar.gz"

[".oh-my-zsh/custom/plugins/you-should-use"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/MichaelAquilina/zsh-you-should-use/archive/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-completions"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-core"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/hadenlabs/zsh-core/archive/develop.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-notify"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/luismayta/zsh-notify/archive/develop.tar.gz"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
exact = true
refreshPeriod = "168h"
stripComponents = 1
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
