---
# Common commands:
# poetry run pre-commit autoupdate
# poetry run pre-commit install
# poetry run pre-commit run --all-files --hook-stage commit
# poetry run pre-commit run --all-files --hook-stage push
# poetry run doit run pre_commit_hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: private_keybindings.json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: pretty-format-json
        args: [--autofix]
        exclude: private_keybindings.json
      # Conflicts with ordering by poetry
      # - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: gh_extensions.*
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        exclude: private_dot_p10k\.zsh
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.38.0
    hooks:
      - id: commitizen
        additional_dependencies: [cz_legacy]
        stages: [commit-msg]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-beautysh
          - mdformat-black
          - mdformat-config
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-tables
          - mdformat-toc
          - mdformat-web
        exclude: _.*\.md|CHANGELOG\.md
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      # Can't generate baseline with Py 3.8. Use exclude regex rules instead
      # See: https://github.com/Yelp/detect-secrets/issues/452
      - id: detect-secrets
        # args: ["--baseline", ".secrets.baseline"]
        exclude: poetry\.lock|.*/cassettes/.*\.yaml
        stages: [push]
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.1.1
    hooks:
      - id: yamlfix
        exclude: \.copier-answers\.yml
        types_or: []
        types: [file, yaml]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args: [--severity=warning]
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
  - repo: local
    hooks:
      - id: copier-forbidden-files
        name: copier_forbidden_files
        # yamllint disable-line rule:line-length
        entry: found copier update rejection files; review them and remove them (https://copier.readthedocs.io/en/stable/updating/)
        language: fail
        files: \.rej$
