---
# Skip prompt to create a new repository if one not present
# Allows for more seamlessly launching lazygit from anywhere and switching context with ctrl+r
notARepository: skip

# Without Enter, I don't see the result of the process and still have the key input error
# https://github.com/jesseduffield/lazygit/issues/1576
# promptToReturnFromSubprocess: false

customCommands:
  # Override push to be a subprocess to see pre-commit output
  - key: P
    description: Git Push with Subprocess
    command: git push
    context: global
    subprocess: true
  - key: <f7>
    description: Git Push (force) with Subprocess
    command: git push --force
    context: global
    subprocess: true
  - key: <c-o>
    description: View the GitHub PR
    command: gh pr view --web
    context: localBranches
    subprocess: true
  - key: "O"
    context: "global"
    # FIXME: These don't open files from commit history
    command: "subl {{.SelectedFile.Name | quote}}"
    description: "Open file with Sublime"
  - key: "o"
    context: "global"
    command: "open {{.SelectedFile.Name | quote}} -a {{.Form.App | quote}}"
    description: "Choose application to open with"
    prompts:
      - type: "input"
        title: "Which application?"
        key: "App"
        suggestions:
          command: "echo -n 'Firefox\nPreview\nExcel\nNumbers\nVisual\ Studio\ Code\nRStudio\nSublime\ Text\nObsidian'"
  # Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
  - key: <c-a>
    description: Add Staged Files to Last Commit
    command: export _MSG=$(git show -s --format=%s) && git reset --soft HEAD~1 && git commit --message "$_MSG" --no-verify
    context: files
    subprocess: true
  - key: w
    description: Commit with `--no-verify`
    command: git commit --message {{.Form.Message | quote}} --no-verify
    context: files
    subprocess: true
    prompts:
      - type: input
        title: "(No Verify) Commit Message:"
        key: "Message"
        initialValue: ""
  - key: <f11>
    description: Delete merged PR branches with gh-poi
    command: gh poi
    context: localBranches
    subprocess: true
  - key: <f12>
    description: Publish local branch to origin
    command: git push -u origin $(git rev-parse --abbrev-ref HEAD)
    context: localBranches
    loadingText: Publishing local branch...
    subprocess: true
  # More from the wiki: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium
  - key: <f10>
    description: Committing via Commitizen (git cz)
    command: git cz
    context: files
    loadingText: Opening commitizen commit tool
    subprocess: true
  - key: N
    description: create annotated tag
    command: git tag -a {{index .PromptResponses 0}} -m "{{index .PromptResponses 1}}"
    context: tags
    prompts:
      - type: input
        title: "Annotated tag name:"
      - type: input
        title: "Annotated tag message:"
  - key: o
    description: Create Pull Request with gh
    command: gh pr create --assignee=@me --fill --web
    context: localBranches
    loadingText: Creating pull request on GitHub
  - key: <f3>
    prompts:
      - type: input
        title: "PR id:"
    command: hub pr checkout {{index .PromptResponses 0}}
    context: localBranches
    loadingText: checking out PR
  - key: <c-p>
    description: prune deleted remote branches
    command: git remote prune {{.SelectedRemote.Name}}
    context: remotes
    loadingText: Pruning...
  - key: <c-f>
    description: Fetch a remote branch as a new local branch
    command: git fetch {{index .SelectedRemote.Name }} {{index .PromptResponses 0}}:{{index .PromptResponses 1}}
    context: remotes
    prompts:
      - type: input
        title: Remote Branch Name
        initialValue: ""
      - type: input
        title: New Local Branch Name
        initialValue: ""
    loadingText: fetching branch
keybinding:
  branches:
    # Flipped to match rename of commit
    rebaseBranch: R
    renameBranch: r
  universal:
    openFile: "e" # null should work, but wasn't. So assign to e to overlap with edit
gui:
  expandFocusedSidePanel: true
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  theme:
    selectedLineBgColor:
      - default # Bold with no background
    selectedRangeBgColor:
      - default # Bold with no background
    cherryPickedCommitBgColor:
      - reverse # High Contrast
    cherryPickedCommitFgColor:
      - reverse # High Contrast
  showIcons: true
git:
  # Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    colorArg: always
    pager: delta --paging=never --true-color=never
  log:
    showWholeGitGraph: true
# More configuration: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
