# Skip prompt to create a new repository if one not present
# Allows for more seamlessly launching lazygit from anywhere and switching context with ctrl+r
notARepository: 'skip'

customCommands:
  # Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
  - key: '<f8>'
    description: 'Add Staged Files to Last Commit'
    command: 'export _MSG=$(git show -s --format=%s) && git reset --soft HEAD~1 && git commit --message "$_MSG" --no-verify'
    context: 'files'
    subprocess: true
  - key : 'w'
    description: 'Commit with `--no-verify`'
    command: 'git commit --message "{{index .PromptResponses 0}}" --no-verify'
    context: 'files'
    subprocess: true
    prompts:
      - type: 'input'
        title: 'Commit Message:'
        initialValue: ''
  - key: '<f11>'
    command: 'gh poi'
    context: 'localBranches'
    subprocess: true
  - key: '<f12>'
    description: 'Publish local branch to origin'
    command: 'git push -u origin $(git rev-parse --abbrev-ref HEAD)'
    context: 'localBranches'
    loadingText: 'Publishing local branch...'
  # More from the wiki: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium
  - key : 'N'
    description: 'create annotated tag'
    command: 'git tag -a {{index .PromptResponses 0}} -m "{{index .PromptResponses 1}}"'
    context: 'tags'
    prompts:
      - type: 'input'
        title: 'Annotated tag name:'
      - type: 'input'
        title: 'Annotated tag message:'
  - key: '<c-r>'
    command: 'gh pr create --fill --web'
    context: 'global'
    loadingText: 'Creating pull request on GitHub'
  - key: 'v' # couldn't think of a better keybinding
    prompts:
      - type: 'input'
        title: 'PR id:'
    command: 'hub pr checkout {{index .PromptResponses 0}}'
    context: 'localBranches'
    loadingText: 'checking out PR'
  - key: '<c-p>'
    command: 'git remote prune {{.SelectedRemote.Name}}'
    context: 'remotes'
    loadingText: 'Pruning...'
    description: 'prune deleted remote branches'
git:
  # Docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# More configuration: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
