# # where to store your database, default is your system data directory
# # linux/mac: ~/.local/share/atuin/history.db
# # windows: %USERPROFILE%/.local/share/atuin/history.db
# db_path = "~/.history.db"

# # Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = true

# [stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
# common_subcommands = [
# "cargo",
# "go",
# "git",
# "npm",
# "yarn",
# "pnpm",
# "kubectl",
# ]
#
# Set commands that should be totally stripped and ignored from stats
# common_prefix = ["sudo"]
