# Tips:
# - Add post-install hooks with: `mise config set tools.node.postinstall "npm install -g neovim"`
# = Manage environment with `mise set SHEARS_SUBDIR=test` and `mise settings`
# - Share uv-installed Python using `mise sync python --uv`

[env]
MISE_NPM_BUN = "true"
MISE_PYTHON_UV_VENV_AUTO = "true"

[settings]
disable_hints = ["python_multi"]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
npm.package_manager = "bun"
pipx.uvx = true

[tools]
python = "3.14.2"
actionlint = "latest"
bun = "latest"
"cargo:selene" = "latest"
"cargo:tree-sitter-cli" = "latest"
deno = "latest"
flyctl = "latest"
go = "latest"
"go:github.com/boyter/dcd" = "latest"
"go:github.com/dhth/act3" = "latest"
"go:github.com/idursun/jjui/cmd/jjui" = "latest"
"go:github.com/merschformann/gotz" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
hk = "latest"
lua-language-server = "latest"
lychee = "latest"
neovim = "nightly"
node = "lts"
# "npm:@ampcode/cli" = "latest"
"npm:@browsermcp/mcp" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@posthog/cli" = "latest"
"npm:@qodo/command" = "latest"
"npm:bash-language-server" = "latest"
"npm:cchistory" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:jj-stack" = "latest"
"npm:stylelint" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:beautysh" = "latest"
"pipx:claude-conversation-extractor" = "latest"
"pipx:code2flow" = "latest"
"pipx:copier" = "latest"
"pipx:copier-template-tester" = "latest"
"pipx:em-keyboard" = "latest"
"pipx:git-filter-repo" = "latest"
"pipx:harlequin" = {extras = "postgres", version = "latest"}
"pipx:macnotesapp" = "latest"
"pipx:mypy-silent" = "latest"
"pipx:norwegianblue" = "latest"
"pipx:pint" = "latest"
"pipx:pygments" = "latest"
"pipx:pylint" = "latest"
"pipx:pyright" = "latest"
"pipx:pysentry-rs" = "latest"
"pipx:pytest-watcher" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:sqlit-tui" = {extras = "postgres", version = "latest"}
"pipx:toml-sort" = "latest"
"pipx:tox" = {uvx_args = "--with tox-uv>=1.29.0", version = "latest"}
"pipx:trcli" = "latest"
"pipx:uv-secure" = "latest"
"pipx:watchgha" = "latest"
"pipx:whisperlivekit" = {uvx_args = "--with torchaudio", version = "latest"}
pkl = "latest"
ripsecrets = "latest" # pragma: allowlist secret
shellcheck = "latest"
typos = "latest"
watchexec = "latest"
yq = "latest"
