[settings]
disable_hints = ["python_multi"]
disable_tools = ["extract-msg", "textract-py3"]
experimental = true
pipx_uvx = true

[settings.python]
compile = true

[tools]
python = "latest"
"cargo:lazyjj" = "latest"
go = "latest"
"go:github.com/boyter/dcd" = "latest"
"go:github.com/merschformann/gotz" = "latest"
node = "latest"
"pipx:black" = "latest"
"pipx:code2flow" = "latest"
"pipx:copier" = "latest"
"pipx:copier-template-tester" = "latest"
"pipx:extract-msg" = "latest"
"pipx:macnotesapp" = "latest"
"pipx:mypy-silent" = "latest"
"pipx:poetry" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pygments" = "latest"
"pipx:pylint" = "latest"
"pipx:pyright" = "latest"
"pipx:pytest-watcher" = "latest"
"pipx:ruff" = "latest"
"pipx:tail-jsonl" = "latest"
"pipx:textract-py3" = "latest"
"pipx:toml-sort" = "latest"
"pipx:tox" = "latest"
"pipx:trcli" = "latest"
"pipx:watchgha" = "latest"
terraform = "latest"
watchexec = "latest"
