[settings]
disable_hints = ["python_multi"]
disable_tools = ["extract-msg", "textract-py3"]
experimental = true
pipx_uvx = true

[tools]
python = "latest"
"cargo:lazyjj" = "latest"
go = "latest"
node = "latest"
"pipx:black" = "latest"
"pipx:code2flow" = "latest"
"pipx:copier" = "latest"
"pipx:copier-template-tester" = "latest"
"pipx:macnotesapp" = "latest"
"pipx:mypy-silent" = "latest"
"pipx:poetry" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pygments" = "latest"
"pipx:ruff" = "latest"
"pipx:toml-sort" = "latest"
"pipx:watchgha" = "latest"
watchexec = "latest"
