---
prSections:
  - title: Needs My Review
    filters: archived:false is:pr is:open review-requested:@me
  - title: My Internal PRs
    filters: archived:false is:pr is:open author:@me org:KyleKing
  - title: My External PRs
    filters: archived:false is:pr is:open author:@me -org:KyleKing
  - title: Mentions Me
    filters: archived:false is:pr is:open mentions:@me
  - title: Reviewer
    filters: archived:false is:pr is:open repo:roaminsight/reviewer
  - title: Roam PRs with Review Required (KB's View)
    filters: archived:false is:pr is:open user:roaminsight draft:false -review:approved
issuesSections:
  - title: Assigned
    filters: archived:false is:issue is:open assignee:@me
  - title: My Internal Issues
    filters: archived:false is:issue is:open author:@me org:KyleKing
  - title: My External Issues
    filters: archived:false is:issue is:open author:@me -org:KyleKing
  - title: Mentions Me
    filters: archived:false is:issue is:open mentions:@me
  - title: Reviewer
    filters: archived:false is:issue is:open repo:roaminsight/reviewer
  - title: My Projects
    filters: archived:false is:issue is:open org:KyleKing
  - title: 'Milestone: Current'
    filters: archived:false is:issue is:open assignee:@me milestone:"current tasks"
  - title: 'Milestone: Next'
    filters: archived:false is:issue is:open assignee:@me milestone:"next tasks"
  - title: 'Milestone: Blue Sky'
    filters: archived:false is:issue is:open assignee:@me milestone:"blue sky"
  - title: 'Milestone: None'
    filters: archived:false is:issue is:open assignee:@me no:milestone

defaults:
  preview:
    open: true
    width: 90
  prsLimit: 50
  issuesLimit: 50
  view: prs
keybindings:
  prs: []
repoPaths: {}
