---
prSections:
  - title: My Work
    filters: author:@me org:roaminsight archived:false is:open sort:updated-desc
  - title: Needs My Review
    filters: review-requested:@me archived:false is:open sort:updated-desc
  - title: My Non-Work
    filters: author:@me -org:roaminsight archived:false is:open sort:updated-desc
  - title: Work PRs Pending Review (KB's View)
    filters: org:roaminsight draft:false -review:approved -author:app/dependabot archived:false is:open sort:updated-desc
issuesSections:
  - title: Assigned
    filters: assignee:@me archived:false is:open sort:updated-desc
  - title: Any Internal Issues
    filters: org:KyleKing archived:false is:open sort:updated-desc
  - title: My External Issues
    filters: -org:KyleKing author:@me archived:false is:open sort:updated-desc
  - title: Mentions Me
    filters: mentions:@me archived:false is:open sort:updated-desc
  - title: Roaminsight
    filters: org:roaminsight archived:false is:open sort:updated-desc

defaults:
  preview:
    open: true
    width: 90
  prsLimit: 25
  issuesLimit: 25
  view: prs
keybindings:
  prs: []
repoPaths: {}
smartFilteringAtLaunch: false
