board:
  id: 26
  name: PPLMS Execution Board
  type: kanban
epic:
  name: customfield_10011
  link: customfield_10014
installation: Cloud
issue:
  fields:
    custom:
      - name: Environment
        key: customfield_10070
        schema:
          datatype: option
      - name: Application
        key: customfield_10071
        schema:
          datatype: option-with-child
      - name: Actual End (migrated)
        key: customfield_10072
        schema:
          datatype: datetime
      - name: Complexity
        key: customfield_10073
        schema:
          datatype: option
      - name: Gantt Options
        key: customfield_10074
        schema:
          datatype: array
          items: option
      - name: Baseline Start
        key: customfield_10075
        schema:
          datatype: datetime
      - name: Baseline End
        key: customfield_10076
        schema:
          datatype: datetime
      - name: Date of Baselining
        key: customfield_10077
        schema:
          datatype: datetime
      - name: Actual Start (migrated)
        key: customfield_10078
        schema:
          datatype: datetime
      - name: Baseline Effort
        key: customfield_10079
        schema:
          datatype: number
      - name: Parties impacted
        key: customfield_10060
        schema:
          datatype: string
      - name: Terms of service (link)
        key: customfield_10061
        schema:
          datatype: string
      - name: Manager
        key: customfield_10062
        schema:
          datatype: user
      - name: Privacy policy (link)
        key: customfield_10063
        schema:
          datatype: string
      - name: If "Yes"
        key: customfield_10064
        schema:
          datatype: string
      - name: If vendor has published a breach report
        key: customfield_10065
        schema:
          datatype: string
      - name: Vendor Name
        key: customfield_10066
        schema:
          datatype: string
      - name: If no compliance, provide links that describe the following at a minimum
        key: customfield_10067
        schema:
          datatype: string
      - name: Budget
        key: customfield_10068
        schema:
          datatype: string
      - name: Story Points
        key: customfield_10069
        schema:
          datatype: number
      - name: Type of data in scope
        key: customfield_10050
        schema:
          datatype: string
      - name: Breach of law or ethics impact on Roam
        key: customfield_10051
        schema:
          datatype: option
      - name: External Link
        key: customfield_10052
        schema:
          datatype: string
      - name: Product or area impacted
        key: customfield_10053
        schema:
          datatype: array
          items: option
      - name: Was PHI returned prior to being used for an improper purpose?
        key: customfield_10054
        schema:
          datatype: string
      - name: Compliance level (and link to website)
        key: customfield_10055
        schema:
          datatype: string
      - name: Industry recognized vendor
        key: customfield_10056
        schema:
          datatype: array
          items: option
      - name: Customer
        key: customfield_10057
        schema:
          datatype: array
          items: option
      - name: Epic/Theme
        key: customfield_10058
        schema:
          datatype: array
          items: string
      - name: Urgency
        key: customfield_10059
        schema:
          datatype: option
      - name: Environment Info
        key: customfield_10049
        schema:
          datatype: string
      - name: Needs for vendor
        key: customfield_10040
        schema:
          datatype: string
      - name: Availability impact on Roam
        key: customfield_10041
        schema:
          datatype: option
      - name: Properly licensed open source software (link)
        key: customfield_10042
        schema:
          datatype: string
      - name: Developer
        key: customfield_10043
        schema:
          datatype: user
      - name: Request Type (migrated)
        key: customfield_10044
        schema:
          datatype: option
      - name: Release Notes
        key: customfield_10045
        schema:
          datatype: string
      - name: What value would it provide if solved?
        key: customfield_10047
        schema:
          datatype: string
      - name: What immediate steps were taken to mitigate an impermissible use or disclosure?
        key: customfield_10048
        schema:
          datatype: string
      - name: Severity
        key: customfield_10038
        schema:
          datatype: option
      - name: Committed Date
        key: customfield_10039
        schema:
          datatype: date
      - name: Category
        key: customfield_10030
        schema:
          datatype: option
      - name: Compass
        key: customfield_10033
        schema:
          datatype: string
      - name: User
        key: customfield_10034
        schema:
          datatype: user
      - name: High Level Size
        key: customfield_10035
        schema:
          datatype: number
      - name: What problem is it trying to solve?
        key: customfield_10036
        schema:
          datatype: string
      - name: Nature & Scope of Incident
        key: customfield_10037
        schema:
          datatype: string
      - name: Open forms
        key: customfield_10027
        schema:
          datatype: number
      - name: Submitted forms
        key: customfield_10028
        schema:
          datatype: number
      - name: Total forms
        key: customfield_10029
        schema:
          datatype: number
      - name: Sprint
        key: customfield_10020
        schema:
          datatype: array
          items: json
      - name: Flagged
        key: customfield_10021
        schema:
          datatype: array
          items: option
      - name: Target start
        key: customfield_10022
        schema:
          datatype: date
      - name: Target end
        key: customfield_10023
        schema:
          datatype: date
      - name: "[CHART] Date of First Response"
        key: customfield_10024
        schema:
          datatype: datetime
      - name: "[CHART] Time in Status"
        key: customfield_10025
        schema:
          datatype: any
      - name: Locked forms
        key: customfield_10026
        schema:
          datatype: number
      - name: Story point estimate
        key: customfield_10016
        schema:
          datatype: number
      - name: Issue color
        key: customfield_10017
        schema:
          datatype: string
      - name: Parent Link
        key: customfield_10018
        schema:
          datatype: any
      - name: Rank
        key: customfield_10019
        schema:
          datatype: any
      - name: Request Type
        key: customfield_10010
        schema:
          datatype: sd-customerrequesttype
      - name: Epic Status
        key: customfield_10012
        schema:
          datatype: option
      - name: Epic Color
        key: customfield_10013
        schema:
          datatype: string
      - name: Start date
        key: customfield_10015
        schema:
          datatype: date
      - name: Change type
        key: customfield_10005
        schema:
          datatype: option
      - name: Change risk
        key: customfield_10006
        schema:
          datatype: option
      - name: Change reason
        key: customfield_10007
        schema:
          datatype: option
      - name: Actual start
        key: customfield_10008
        schema:
          datatype: datetime
      - name: Actual end
        key: customfield_10009
        schema:
          datatype: datetime
      - name: Velocity %
        key: customfield_10080
        schema:
          datatype: number
      - name: Planned Start
        key: customfield_10081
        schema:
          datatype: datetime
      - name: Planned End
        key: customfield_10082
        schema:
          datatype: datetime
      - name: Start date (migrated)
        key: customfield_10083
        schema:
          datatype: date
      - name: End date
        key: customfield_10084
        schema:
          datatype: date
      - name: Release Notes (migrated)
        key: customfield_10085
        schema:
          datatype: array
          items: option
      - name: QA Verified
        key: customfield_10086
        schema:
          datatype: array
          items: option
      - name: Development
        key: customfield_10000
        schema:
          datatype: any
      - name: Team
        key: customfield_10001
        schema:
          datatype: any
      - name: Organizations
        key: customfield_10002
        schema:
          datatype: array
          items: sd-customerorganization
      - name: Approvers
        key: customfield_10003
        schema:
          datatype: array
          items: user
      - name: Impact
        key: customfield_10004
        schema:
          datatype: option
  types:
    - id: "10000"
      name: Epic
      handle: Epic
      subtask: false
    - id: "10004"
      name: Story
      handle: Story
      subtask: false
    - id: "10019"
      name: Task
      handle: Task
      subtask: false
    - id: "10009"
      name: Bug
      handle: Bug
      subtask: false
    - id: "10015"
      name: Sub-task
      handle: Sub-task
      subtask: true
login: kyle.king@parexel.com
project:
  key: PPLMS
  type: classic
server: https://parexelailabs.atlassian.net
