# This is maintain by github.com/nonepork
# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
# I know this is not really that "vim", but the control flow is different.

cancel_typing = ['', 'esc']
change_panel_mode = ['', 'm']
close_file_panel = ['', 'q']
compress_file = ['', 'ctrl+a']
confirm = ['', 'enter']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['', 'enter']
# file operations
copy_items = ['', 'y']
# file panel control
create_new_file_panel = ['', 'n']
cut_items = ['', 'x']
delete_items = ['', 'd']
# compress and extract
extract_file = ['', 'ctrl+e']
# create file/directory and rename
file_panel_item_create = ['', 'a']
file_panel_item_rename = ['', 'r']
file_panel_select_all_items = ['', 'A']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cananot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['', 'J']
file_panel_select_mode_items_select_up = ['', 'K']
focus_on_metadata = ['', 'ctrl+m']
# change focus
focus_on_process_bar = ['', 'ctrl+p']
focus_on_sidebar = ['', 'ctrl+s']
list_down = ['', 'j']
# movement
list_up = ['', 'k']
next_file_panel = ['', 'tab']
open_current_directory_with_editor = ['', 'E']
# editor
open_file_with_editor = ['', 'e']
open_help_menu = ['', '?']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['', '-']
paste_items = ['', 'p']
# other
pinned_directory = ['', 'P']
previous_file_panel = ['', 'shift+tab']
quit = ['', 'ctrl+c'] # also know as, theprimeagen troller
search_bar = ['', '/']
toggle_dot_file = ['', '.']
toggle_file_preview_panel = ['', 'f']
